"""Source-map based backtracking from orthophoto pixel to raw image pixel.

Uses the odm_orthophoto_sources.tif generated by ODM which contains the
authoritative mapping from each orthophoto pixel to its source raw image
and pixel coordinates.

This is more reliable than camera projection because:
1. ODM creates this during orthophoto generation with exact pixel correspondence
2. No need to match projection formulas between different camera models
3. Handles all the coordinate system conversions internally
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import rasterio

from ..utils.logger import get_logger

logger = get_logger(__name__)


@dataclass
class SourceMapResult:
    """Result of source-map lookup."""

    view_id: int  # Camera index (0-based) from NVM
    raw_pixel_x: float  # X coordinate in raw image (sub-pixel precision)
    raw_pixel_y: float  # Y coordinate in raw image (sub-pixel precision)
    image_name: Optional[str] = None  # Resolved image name


class SourceMapBacktracker:
    """Backtrack orthophoto pixels to raw image pixels using ODM source-map.

    The source-map is a 3-band Float32 GeoTIFF where:
    - Band 1: view_id (camera index from NVM, 0-based, as float)
    - Band 2: raw_x (x coordinate in raw image, sub-pixel precision)
    - Band 3: raw_y (y coordinate in raw image, sub-pixel precision)

    Invalid pixels have NaN values.
    Legacy uint16 source-maps (view_id = 65535 for invalid) are also supported.
    """

    INVALID_VIEW_ID = 65535  # For backward compatibility with uint16 source-maps

    def __init__(
        self,
        source_map_path: Path,
        nvm_path: Optional[Path] = None,
    ) -> None:
        """
        Initialize source-map backtracker.

        Args:
            source_map_path: Path to odm_orthophoto_sources.tif
            nvm_path: Optional path to reconstruction.nvm for view_id to image name mapping
        """
        self.available = False
        self.view_ids: Optional[np.ndarray] = None
        self.raw_x: Optional[np.ndarray] = None
        self.raw_y: Optional[np.ndarray] = None
        self.width = 0
        self.height = 0
        self.view_id_to_name: Dict[int, str] = {}

        if not source_map_path.exists():
            logger.warning(f"Source map not found: {source_map_path}")
            return

        try:
            with rasterio.open(source_map_path) as src:
                # Read all 3 bands as float32 (supports both new float32 and legacy uint16)
                self.view_ids = src.read(1).astype(np.float32)
                self.raw_x = src.read(2).astype(np.float32)
                self.raw_y = src.read(3).astype(np.float32)
                self.height, self.width = self.view_ids.shape

                # Store transform for coordinate conversion
                self.transform = src.transform

            logger.info(
                f"Loaded source-map: {self.width}x{self.height}, "
                f"valid pixels: {np.sum(self.view_ids != self.INVALID_VIEW_ID)}"
            )
        except Exception as e:
            logger.warning(f"Failed to load source-map: {e}")
            return

        # Parse NVM to get view_id to image name mapping
        if nvm_path and nvm_path.exists():
            try:
                self.view_id_to_name = self._parse_nvm(nvm_path)
                logger.info(f"Loaded NVM with {len(self.view_id_to_name)} cameras")
            except Exception as e:
                logger.warning(f"Failed to parse NVM: {e}")

        self.available = True

    def _parse_nvm(self, nvm_path: Path) -> Dict[int, str]:
        """Parse reconstruction.nvm to get view_id to image name mapping."""
        view_map = {}

        with open(nvm_path, 'r') as f:
            lines = f.readlines()

        # Find NVM_V3 header
        i = 0
        while i < len(lines) and 'NVM_V3' not in lines[i]:
            i += 1
        i += 1  # Skip header line

        # Skip empty lines
        while i < len(lines) and lines[i].strip() == '':
            i += 1

        if i >= len(lines):
            return view_map

        num_cameras = int(lines[i].strip())
        i += 1

        for view_idx in range(num_cameras):
            if i + view_idx >= len(lines):
                break
            parts = lines[i + view_idx].strip().split()
            if not parts:
                continue

            image_name = parts[0]
            # Clean up path - extract just filename
            if '/' in image_name:
                image_name = image_name.split('/')[-1]
            # Remove .tif extension if present (NVM adds this internally)
            if image_name.endswith('.tif'):
                image_name = image_name[:-4]

            view_map[view_idx] = image_name

        return view_map

    def backtrack(
        self,
        ortho_x: float,
        ortho_y: float,
    ) -> Optional[SourceMapResult]:
        """
        Look up raw image pixel for an orthophoto pixel.

        Args:
            ortho_x: X coordinate in orthophoto (pixels, in source-map resolution)
            ortho_y: Y coordinate in orthophoto (pixels, in source-map resolution)

        Returns:
            SourceMapResult with view_id, raw_x, raw_y, and image_name, or None if invalid
        """
        if not self.available:
            return None

        # Round to nearest pixel
        col = int(round(ortho_x))
        row = int(round(ortho_y))

        # Check bounds
        if col < 0 or col >= self.width or row < 0 or row >= self.height:
            logger.debug(f"Source-map lookup out of bounds: ({col}, {row})")
            return None

        view_id_val = self.view_ids[row, col]

        # Check for invalid pixel (NaN for float32, 65535 for legacy uint16)
        if np.isnan(view_id_val) or view_id_val == self.INVALID_VIEW_ID or view_id_val == 0:
            logger.debug(f"Invalid view_id at ({col}, {row}): {view_id_val}")
            return None

        view_id = int(view_id_val)
        raw_x = float(self.raw_x[row, col])
        raw_y = float(self.raw_y[row, col])

        # Check for NaN in coordinates (float32 source-maps use NaN for invalid)
        if np.isnan(raw_x) or np.isnan(raw_y):
            logger.debug(f"Invalid raw coordinates at ({col}, {row}): NaN")
            return None

        # Get image name from view_id
        image_name = self.view_id_to_name.get(view_id)

        logger.debug(
            f"Source-map lookup: ortho=({col}, {row}) -> "
            f"view_id={view_id}, raw=({raw_x}, {raw_y}), image={image_name}"
        )

        return SourceMapResult(
            view_id=view_id,
            raw_pixel_x=raw_x,
            raw_pixel_y=raw_y,
            image_name=image_name,
        )

    def backtrack_with_search(
        self,
        ortho_x: float,
        ortho_y: float,
        search_radius: int = 5,
    ) -> Optional[SourceMapResult]:
        """
        Look up raw image pixel with search radius for robustness.

        If the exact pixel has invalid source-map data, searches nearby pixels
        and returns the most common valid result.

        Args:
            ortho_x: X coordinate in orthophoto (pixels)
            ortho_y: Y coordinate in orthophoto (pixels)
            search_radius: Radius to search if exact pixel is invalid

        Returns:
            SourceMapResult or None if no valid pixels found
        """
        # First try exact pixel
        result = self.backtrack(ortho_x, ortho_y)
        if result is not None:
            return result

        if not self.available:
            return None

        # Search nearby pixels
        col = int(round(ortho_x))
        row = int(round(ortho_y))

        # Collect all valid results in search area
        from collections import Counter
        results: Counter = Counter()

        for dy in range(-search_radius, search_radius + 1):
            for dx in range(-search_radius, search_radius + 1):
                c = col + dx
                r = row + dy

                if c < 0 or c >= self.width or r < 0 or r >= self.height:
                    continue

                view_id_val = self.view_ids[r, c]
                if np.isnan(view_id_val) or view_id_val == self.INVALID_VIEW_ID or view_id_val == 0:
                    continue

                view_id = int(view_id_val)
                raw_x = float(self.raw_x[r, c])
                raw_y = float(self.raw_y[r, c])

                # Skip if coordinates are NaN
                if np.isnan(raw_x) or np.isnan(raw_y):
                    continue

                # Count by view_id (image selection is most important)
                results[view_id] += 1

        if not results:
            logger.debug(
                f"No valid source-map pixels in {search_radius}px radius around ({col}, {row})"
            )
            return None

        # Get the most common view_id
        best_view_id = results.most_common(1)[0][0]

        # Find a pixel with this view_id to get raw coordinates
        for dy in range(-search_radius, search_radius + 1):
            for dx in range(-search_radius, search_radius + 1):
                c = col + dx
                r = row + dy

                if c < 0 or c >= self.width or r < 0 or r >= self.height:
                    continue

                view_id_val = self.view_ids[r, c]
                if not np.isnan(view_id_val) and int(view_id_val) == best_view_id:
                    raw_x = float(self.raw_x[r, c])
                    raw_y = float(self.raw_y[r, c])
                    if np.isnan(raw_x) or np.isnan(raw_y):
                        continue
                    image_name = self.view_id_to_name.get(best_view_id)

                    logger.debug(
                        f"Source-map search hit: ortho=({col}, {row}) radius={search_radius} -> "
                        f"view_id={best_view_id}, raw=({raw_x}, {raw_y}), image={image_name}"
                    )

                    return SourceMapResult(
                        view_id=best_view_id,
                        raw_pixel_x=raw_x,
                        raw_pixel_y=raw_y,
                        image_name=image_name,
                    )

        return None

    def get_coverage_stats(self) -> Dict[str, int]:
        """Get coverage statistics for the source-map."""
        if not self.available:
            return {"available": False}

        total = self.width * self.height
        # Count valid pixels (not NaN and not INVALID_VIEW_ID)
        valid = int(np.sum(~np.isnan(self.view_ids) & (self.view_ids != self.INVALID_VIEW_ID) & (self.view_ids != 0)))

        return {
            "available": True,
            "width": self.width,
            "height": self.height,
            "total_pixels": total,
            "valid_pixels": valid,
            "coverage_percent": round(100 * valid / total, 2) if total > 0 else 0,
        }
